server:
  port: 8088
logging:
  file: rabbitmq-using/logs/rabbitmq-using.log
  level:
    root: info
spring:
  ####amqp
  rabbitmq:
    addresses: 47.105.195.242:5672, 47.105.191.177:5672, 47.105.148.191:5972
    username: mainfunc
    password: mainfunc
    virtual-host: mf_dev
    #不指定心跳超时
    requested-heartbeat: 0
    #连接超时
    connection-timeout: 60000
    ##
    #发布确认
    publisher-confirms: true
    #发布返回
    publisher-returns: true
    ##
    listener:
      direct:
        #消费确认
        acknowledge-mode: manual
        retry:
          enabled: true
      simple:
            #容器自动启动
            auto-startup: false
            #消费确认
            acknowledge-mode: manual
            #并发消费限制
            concurrency: 1
            max-concurrency: 5
            #一次性消费限制
            prefetch: 1
    ##
    template:
      retry:
        enabled: true
    ##
    exchange:
      msg-fault: msg.fault
    routing-key:
      fault-info: KFltInfo
    queue:
      fault-info: QFltInfo